# Generated by Django 4.1.5 on 2023-02-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('faculty', models.CharField(default='Engineering', max_length=250)),
                ('department', models.CharField(default='Information and Comunication Technology', max_length=250)),
                ('program', models.CharField(max_length=250)),
                ('batch', models.CharField(max_length=10)),
                ('session', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=250)),
                ('college', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField()),
                ('fb_id', models.CharField(max_length=250)),
                ('hometown', models.CharField(max_length=250)),
                ('present_address', models.CharField(default='', max_length=250)),
                ('in_hall', models.BooleanField()),
            ],
        ),
    ]
