# Generated by Django 4.1.7 on 2023-03-13 11:15

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='reg_no',
            new_name='student_id',
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(choices=[('ICT', 'Information and Communication Technology')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='faculty',
            field=models.CharField(choices=[('Engineering', 'Engineering')], max_length=20),
        ),
        migrations.AlterField(
            model_name='students',
            name='fb_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='program',
            field=models.CharField(choices=[('IoT', 'Internet of Things')], max_length=20),
        ),
    ]
